// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz-jx-7rpOA2wDsM66LlGni7XvNJVeKXE',
    appId: '1:36726489047:web:fd36a5d37620ff50ebd592',
    messagingSenderId: '36726489047',
    projectId: 'quickbib-2798f',
    authDomain: 'quickbib-2798f.firebaseapp.com',
    storageBucket: 'quickbib-2798f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBrLaYCaSVm-r1xZLebWWPLa1cLhd4pV8',
    appId: '1:36726489047:android:f92135d11b562d58ebd592',
    messagingSenderId: '36726489047',
    projectId: 'quickbib-2798f',
    storageBucket: 'quickbib-2798f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6CM1QIg73NuME3pUnB5snk9gm2Ky273Q',
    appId: '1:36726489047:ios:494cbc9dc6050665ebd592',
    messagingSenderId: '36726489047',
    projectId: 'quickbib-2798f',
    storageBucket: 'quickbib-2798f.appspot.com',
    iosBundleId: 'com.example.quickBib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6CM1QIg73NuME3pUnB5snk9gm2Ky273Q',
    appId: '1:36726489047:ios:494cbc9dc6050665ebd592',
    messagingSenderId: '36726489047',
    projectId: 'quickbib-2798f',
    storageBucket: 'quickbib-2798f.appspot.com',
    iosBundleId: 'com.example.quickBib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz-jx-7rpOA2wDsM66LlGni7XvNJVeKXE',
    appId: '1:36726489047:web:548f5769bb649ff4ebd592',
    messagingSenderId: '36726489047',
    projectId: 'quickbib-2798f',
    authDomain: 'quickbib-2798f.firebaseapp.com',
    storageBucket: 'quickbib-2798f.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: "AIzaSyAz-jx-7rpOA2wDsM66LlGni7XvNJVeKXE",
    appId: "1:36726489047:web:ea3fc8dfecd3e78cebd592",
    messagingSenderId: "36726489047",
    projectId: "quickbib-2798f",
    authDomain: "quickbib-2798f.firebaseapp.com",
    storageBucket: "quickbib-2798f.appspot.com",
  );
}
